name: pokemon_heb
description: Pokemon test.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.7.2+9

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  change_app_package_name: ^1.0.0
  web_socket_channel: 2.2.0
  graphql_flutter: ^5.1.0
  cached_network_image: ^3.0.0
  get: ^4.6.1
  internet_connection_checker: ^0.0.1+3
  flutter_svg: ^1.1.6
  permission_handler: ^6.1.3
  intl: ^0.17.0
  get_storage: ^2.0.3
  geolocator: ^8.2.0
  jwt_decode: ^0.3.1
  sqflite: ^2.0.2
  package_info_plus: ^1.4.2
  device_info_plus: ^4.1.0
  pull_to_refresh: ^2.0.0
  flutter_bootstrap: ^2.0.0
  states_rebuilder: ^6.1.0+1
  responsive_table: ^0.2.0+2
  image_picker: ^0.8.4+4
  jiffy: ^5.0.0
  path_provider: ^2.0.11
  mask_text_input_formatter: ^2.4.0
  email_validator: ^2.1.17
  lazy_load_scrollview: 1.3.0
  dotted_line: ^3.1.0
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  badges: ^2.0.2

flutter_native_splash:
  color: "#1663b2"
  image: assets/img/logo_splash_1152.png
  android: true
  ios: true
  web: false

  android_12:
    image: assets/img/logo_splash_1152.png
    color: "#1663b2"

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/Icon.jpg"
  adaptive_icon_background: "assets/img/Icon.jpg"

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/img/
    - assets/fonts/
    - assets/ca/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Black.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf
        - asset: assets/fonts/TitilliumWeb-ExtraLight.ttf
        - asset: assets/fonts/TitilliumWeb-ExtraLightItalic.ttf
        - asset: assets/fonts/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/TitilliumWeb-Light.ttf
        - asset: assets/fonts/TitilliumWeb-LightItalic.ttf
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf
